### ISSUE TITLE
clientKey and hashToken endpoints are down

### ISSUE THREAD

**Issue by javialbors** [e9x/imsoware#1]
https://imsoware.sys32.dev/clientKey and https://imsoware.sys32.dev/hashToken endpoints are down.

Any information about that?

**Comment by e9x** [comment]
The script serving the API must have crashed. The mmtoken will have to be obtained through other means.

**Comment by javialbors** [comment]
https://imsoware.sys32.dev/source endpoint still works though, which is weird. There is no way to fix / restart the script so that it starts serving again?

Also, could I contact you by any chance to ask you about how did you manage to obtain the mmtoken by scrapping the WASM loader I believe?

Thanks
